### ISSUE TITLE
Refund of non-captured transactions for multi payment

### ISSUE THREAD

**Issue by Jeremy-FT** [lyra/plugin-prestashop#4]
Hi, when you do a refund from the Prestashop module, only non-captured transactions can be refunded for multi payment. As long as the amount of the refund does not exceed the amount of the non-captured transactions, the refund is done. The non-captured transactions are either modified or cancelled. However, it should be possible to make a total or partial refund that exceeds the amount of the non-captured transactions. In this case, the non-captured transactions must be cancelled or modified and the discounted transactions must be refunded, in total or partially.

Thank you !

**Comment by Jeremy-FT** [comment]
> Hi, when you do a refund from the Prestashop module, only non-captured transactions can be refunded for multi payment. As long as the amount of the refund does not exceed the amount of the non-captured transactions, the refund is done. The non-captured transactions are either modified or cancelled. However, it should be possible to make a total or partial refund that exceeds the amount of the non-captured transactions. In this case, the non-captured transactions must be cancelled or modified and the discounted transactions must be refunded, in total or partially.
> 
> Thank you !

**Comment by frachedi** [comment]
Hi, thank you for your report, for the refund of an order (multi payment) we start refund from last transaction to avoid as much as possible to touch the captured transactions (logically are the firsts ones).

So for the non captured transaction: either we change the amount (if refunded amount is less than transaction amount) or we cancel the transaction.

For the captured transactions: we cannot modify or cancel them we create a transaction with amount equal  to the refund amount and type = **CREDIT**

Best regards !

**Comment by Jeremy-FT** [comment]
I totally agree with you for non captured transactions and that work well. I agree too for the captured transaction but in my tests there was no refund (CREDIT) done. I will test again and come back to you.

**Comment by Jeremy-FT** [comment]
Well, I tested again and the refund (CREDIT) of the captured transaction work well ! I must have missed something, sorry !

I noticed something else. I will open a new issue
