### ISSUE TITLE
Wrong order status for full refund

### ISSUE THREAD

**Issue by Jeremy-FT** [lyra/plugin-prestashop#5]
Hi, when a transaction is fully refunded from Lyra BO, the module changes the status of the order to "Refunded with Lyra Collect" and then to "Payment accepted". This should not happen. The order should be set to "Refunded with Lyra Collect" but only if there are no other transactions for the order. If the refund is partial or if there are other payments, Lyra or not, you should not update the order status.

Thanks !

**Comment by frachedi** [comment]
Hi, thank you for your report, i made some tests to reproduce your issue.

For a non-captured transaction, from Lyra BO you can either modify transaction amount or cancel it and this make same changes in the BO PrestaShop for the corresponding order.

For a captured transaction, from Lyra BO you can perform a refund for a partial or the total transaction amount, once you refund the totality of the transaction the order in the BO PrestaShop passes to **"Refunded with Lyra Collect"**

I am not able to reproduce your issue, the order remains in the state **"Refunded with Lyra Collect"**

Best regards !

**Comment by Jeremy-FT** [comment]
Ok, thank you for testing ! I will try again to see if it happen again or not.

**Comment by Jeremy-FT** [comment]
I did more test and I confirm that the problem occur. However I didn't mention that we have a Lyra (BO) notification rule triggered for successful/failed refund.

**Comment by Jeremy-FT** [comment]
> For a non-captured transaction, from Lyra BO you can either modify transaction amount or cancel it and this make same changes in the BO PrestaShop for the corresponding order.

Yes, I agree

> For a captured transaction, from Lyra BO you can perform a refund for a partial or the total transaction amount, once you refund the totality of the transaction the order in the BO PrestaShop passes to **"Refunded with Lyra Collect"**

Yes, I agree too

The "Payment accepted" status that is set after "Refunded with Lyra Collect" happen because we have a Lyra (BO) notification rule triggered for successful/failed refund.

**Comment by frachedi** [comment]
Hi, thank you for your report, i made tests with this new rule u forgot to mention, i reproduce your issue, we will fix it  in the upcoming version.

Best regards !

**Comment by Jeremy-FT** [comment]
Hi, thank you very much I will test that :)
