### ISSUE TITLE
Wrong order status for canceled payment

### ISSUE THREAD

**Issue by Jeremy-FT** [lyra/plugin-prestashop#6]
Hi, when a payment is canceled from Lyra BO (non-captured transaction), the module sets the order status to "Canceled", even if the cancellation is only for a part of the total order amount. The status of the order should be set to "Cancelled" only if the cancellation is equal to the total amount of the order and there is no other payment, Lyra or not, for that order. Another thing, all payments are deleted from the order! Of course, the other payments must not be deleted.

Thanks !

**Comment by frachedi** [comment]
Hi, thank you for your report, i am sorry to not understand what do you mean by "**the cancellation is only for a part of the total order amount**" as i explained you in the issue #5  "For a non-captured transaction, from Lyra BO you can either modify transaction amount or cancel it ..." cancellation is for the totality of the amount of the transaction and not for a part.

Best regards !

**Comment by frachedi** [comment]
Hi, thank you for your report, can you please show me the scenario for making such kind of payment per part for a given order?

Best regards !

**Comment by Jeremy-FT** [comment]
It can happen when an order is payed with multiple means of payments. In this case we can cancel the Lyra payment and therefore the order status must not be "Canceled". In summary the module should check if there is no other payment and the canceled current Lyra payment match the total order amount before setting the order status to "Canceled".

**Comment by frachedi** [comment]
Hi, thank you for your report, exactelly i wanna know how to pay with multiple means of payments, to reproduce your issue?

Best regards !

**Comment by Jeremy-FT** [comment]
You can add payments in the order in prestashop back office for instance

**Comment by frachedi** [comment]
Hi, thank you for your report, i made tests, i reproduce your issue, we will fix it in the upcoming version.

Best regards !
