### ISSUE TITLE
Wrong order status for cancelled refund

### ISSUE THREAD

**Issue by Jeremy-FT** [lyra/plugin-prestashop#7]
Hi, when a refund is cancelled from Lyra BO, the module sets the order status to "Cancelled". In this case the status should not change and moreover should not change to "Cancelled". Indeed the cancellation may be due to an error or the refund may be made by another means.

Thank you !

**Comment by frachedi** [comment]
Hi, thank you for your report, i agree with you, we will fix this issue in the upcoming version.

Best regards !

**Comment by Jeremy-FT** [comment]
Great ! Thanks !
