### ISSUE TITLE
Order_payment not deleted/updated if full/partial refund of captured transaction for multi payment

### ISSUE THREAD

**Issue by Jeremy-FT** [lyra/plugin-prestashop#8]
Hi, when you do a full refund from the Prestashop module I noticed that the non captured transactions are deleted from the order_payment but the captured transaction are not. The captured transactions should be deleted too in case of a full refund.

I also noticed that the captured transaction are not updated according to the refund in case of the partial refund. For instance if you have a multi payment (2 x 250€) with the first transaction captured and you refund 400€, the order_payment of the captured transaction is not updated (250€ -> 100€).

Thanks

**Comment by frachedi** [comment]
Hi, thank you for your report, in the older versions of PrestaShop we were creating payments with negative amount for payments of type **CREDIT**, PrestaShop banned it in the latests versions, we have already decided to fix this issue in the upcomming version.

Best regards !

**Comment by Jeremy-FT** [comment]
Great ! Thank you very much !

**Comment by Jeremy-FT** [comment]
Hi, thank you very much !
